DROP TABLE IF EXISTS lords;
DROP TABLE IF EXISTS planets;

CREATE TABLE lords (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  name VARCHAR(250) NOT NULL,
  age INT NOT NULL
);

CREATE TABLE planets (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  name VARCHAR(250) NOT NULL,
  lord_id INT DEFAULT NULL
);